"use strict";
(() => {
var exports = {};
exports.id = 155;
exports.ids = [155];
exports.modules = {

/***/ 97783:
/***/ ((module) => {

module.exports = require("next/dist/compiled/@edge-runtime/cookies");

/***/ }),

/***/ 28530:
/***/ ((module) => {

module.exports = require("next/dist/compiled/@opentelemetry/api");

/***/ }),

/***/ 54426:
/***/ ((module) => {

module.exports = require("next/dist/compiled/chalk");

/***/ }),

/***/ 40252:
/***/ ((module) => {

module.exports = require("next/dist/compiled/cookie");

/***/ }),

/***/ 32196:
/***/ ((module) => {

module.exports = require("next/dist/compiled/ua-parser-js");

/***/ }),

/***/ 14021:
/***/ ((module) => {

module.exports = import("next/dist/compiled/@vercel/og/index.node.js");;

/***/ }),

/***/ 84964:
/***/ ((__unused_webpack_module, __webpack_exports__, __webpack_require__) => {

// ESM COMPAT FLAG
__webpack_require__.r(__webpack_exports__);

// EXPORTS
__webpack_require__.d(__webpack_exports__, {
  headerHooks: () => (/* binding */ headerHooks),
  originalPathname: () => (/* binding */ originalPathname),
  requestAsyncStorage: () => (/* binding */ requestAsyncStorage),
  routeModule: () => (/* binding */ routeModule),
  serverHooks: () => (/* binding */ serverHooks),
  staticGenerationAsyncStorage: () => (/* binding */ staticGenerationAsyncStorage),
  staticGenerationBailout: () => (/* binding */ staticGenerationBailout)
});

// NAMESPACE OBJECT: ./node_modules/next/dist/build/webpack/loaders/next-metadata-route-loader.js?page=%2Ffavicon.ico%2Froute&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js!./app/favicon.ico?__next_metadata__
var favicon_next_metadata_namespaceObject = {};
__webpack_require__.r(favicon_next_metadata_namespaceObject);
__webpack_require__.d(favicon_next_metadata_namespaceObject, {
  GET: () => (GET),
  dynamic: () => (dynamic)
});

// EXTERNAL MODULE: ./node_modules/next/dist/server/node-polyfill-headers.js
var node_polyfill_headers = __webpack_require__(35387);
// EXTERNAL MODULE: ./node_modules/next/dist/server/future/route-modules/app-route/module.js
var app_route_module = __webpack_require__(29267);
var module_default = /*#__PURE__*/__webpack_require__.n(app_route_module);
// EXTERNAL MODULE: ./node_modules/next/server.js
var server = __webpack_require__(14664);
;// CONCATENATED MODULE: ./node_modules/next/dist/build/webpack/loaders/next-metadata-route-loader.js?page=%2Ffavicon.ico%2Froute&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js!./app/favicon.ico?__next_metadata__


const contentType = "image/x-icon"
const buffer = Buffer.from("AAABAAMAMDAAAAEAIACoJQAANgAAACAgAAABACAAqBAAAN4lAAAQEAAAAQAgAGgEAACGNgAAKAAAADAAAABgAAAAAQAgAAAAAAAAJAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA82ExFfNjLVXyYy2N8mMttvJkLdjyZC3s8mQt+fJkLfnyZC3s8mQt2PJjLbbyYy2N82MtVfJmMxQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8WMrEvNkLWvyZC3H8mQt/vJkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf7yZC3G82UuavFjKxIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPVmKRnyYy2N8mQt9PJkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLfPyZS6L9GQsFwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/gEAE8WUub/JlLfHyZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt9PFkLoD/VSsGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPFjKyTzZC3N8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3L8GYsIwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8mQtT/JlLfHyZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLuDyZS2d8mMuZPJkLj3wYi0i8l4oE/JeKBPwYi0i8mQuPfJjLmTyZC2e82Qt4fJkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt8PJlLEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADyZS1l8mQt/PJkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLfnyZC6c8mItOQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAfJlLDryZS2d8mQt+fJkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLfvyZCxjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJlLWXyZC3+8mQt//JkLf/yZC3/8mQt//JkLf/yZC3+8mQtoPZkLhwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA7mYrHvJlLqLyZC3+8mQt//JkLf/yZC3/8mQt//JkLf/yZC3+8mQsYwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8mMtUPJkLfzyZC3/8mQt//JkLf/yZC3/8mQt//JkLePzZS0/AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPNhMRXyZi0o8mYtKPJmLSjyZi0o82ExFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADzZC5C8mQt5fJkLf/yZC3/8mQt//JkLf/yZC3/8mQt+/JlLEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADxZzAl8mQt8vJkLf/yZC3/8mQt//JkLf/yZC3/8mQtwfJmMxQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA82guFvJjLMPyZC3/8mQt//JkLf/yZC3/8mQt//JkLfDwZiwjAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP9mMwXxZC3O8mQt//JkLf/yZC3/8mQt//JkLf/yZCyy/2AgCAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP9xOQnyZS208mQt//JkLf/yZC3/8mQt//JkLf/yZC3L/4BABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJjLXbyZC3/8mQt//JkLf/yZC3/8mQt//JkLcD/YCAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/cTkJ8mMsw/JkLf/yZC3/8mQt//JkLf/yZC3/8WMtcQAAAAAAAAAAAAAAAAAAAAAAAAAA9WIxGvJkLfTyZC3/8mQt//JkLf/yZC3/8WQt4vJeKBMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA82guFvJkLeXyZC3/8mQt//JkLf/yZC3/8mQt8vRgKxgAAAAAAAAAAAAAAAAAAAAA82Qtj/JkLf/yZC3/8mQt//JkLf/yZC3+82MtPgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPNkLkLyZC3+8mQt//JkLf/yZC3/8mQt//JlLosAAAAAAAAAAAAAAADyXigT8mQt9PJkLf/yZC3/8mQt//JkLf/yZC2eAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADyZS6i8mQt//JkLf/yZC3/8mQt//JkLfPxYysSAAAAAAAAAADxZSxt8mQt//JkLf/yZC3/8mQt//JkLfj2aC8bAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD2YSwd8mQt+fJkLf/yZC3/8mQt//JkLf/zZC5pAAAAAAAAAADyZC3K8mQt//JkLf/yZC3/8mQt//JkLJsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8mQtnvJkLf/yZC3/8mQt//JkLf/yZC3GAAAAAPNoLhbyZC3+8mQt//JkLf/yZC3/8mQt//FmLjcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8mMrO/JkLf/yZC3/8mQt//JkLf/yZC3+82ExFfNlLljyZC3/8mQt//JkLf/yZC3/8mQt3gAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAfNkLeHyZC3/8mQt//JkLf/yZC3/82MtVfNjLJDyZC3/8mQt//JkLf/yZC3/8mQsmwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLZ7yZC3/8mQt//JkLf/yZC3/8mMtjfJkLbfyZC3/8mQt//JkLf/yZC3/8mQsYwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJlLWXyZC3/8mQt//JkLf/yZC3/8mQttfJkLdvyZC3/8mQt//JkLf/yZC3/8mMrOwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLj3yZC3/8mQt//JkLf/yZC3/8mMs2vJkLezyZC3/8mQt//JkLf/yZC3/72gwIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPBkLiHyZC3/8mQt//JkLf/yZC3/8mQs6/JkLfnyZC3/8mQt//JkLf/yZC3/8l4oEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJmMxTyZC3/8mQt//JkLf/yZC3/8mQt+PJkLfnyZC3/8mQt//JkLf/yZC3/8mYzFAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJmMxTyZC3/8mQt//JkLf/yZC3/8mQt+PJkLe3yZC3/8mQt//JkLf/yZC3/72gwIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPBkLiHyZC3/8mQt//JkLf/yZC3/8mQs6/JkLdzyZC3/8mQt//JkLf/yZC3/8mMrOwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLj3yZC3/8mQt//JkLf/yZC3/8mMs2vNkLLjyZC3/8mQt//JkLf/yZC3/8mMsYgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJjLmTyZC3/8mQt//JkLf/yZC3/8mQttfNjLJDyZC3/8mQt//JkLf/yZC3/8mMtmgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJlLZ3yZC3/8mQt//JkLf/yZC3/8mUtjvNlLljyZC3/8mQt//JkLf/yZC3/8mQt3QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/wAAAfJkLuDyZC3/8mQt//JkLf/yZC3/82MtVfNoLhbyZC3+8mQt//JkLf/yZC3/8mQt//FlKzUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPNhKyryZSxR8mUsUfJlLFHyZSxR82ErKgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8mItOfJkLf/yZC3/8mQt//JkLf/yZC3+82guFgAAAADyZC3K8mQt//JkLf/yZC3/8mQt//JjLZoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8mQunPJkLf/yZC3/8mQt//JkLf/yZC3HAAAAAAAAAADxZCxu8mQt//JkLf/yZC3/8mQt//JkLfj1YjEaAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPNhMRXyZi0o8mYtKPJmLSjyZi0o82ExFQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD2ZC4c8mQt+fJkLf/yZC3/8mQt//JkLf/zZS5qAAAAAAAAAADyZjMU82Qt9fJkLf/yZC3/8mQt//JkLf/yZCybAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADyZC2g8mQt//JkLf/yZC3/8mQt//JkLfTxYysSAAAAAAAAAAAAAAAA82MskPJkLf/yZC3/8mQt//JkLf/yZC398mYvPAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPNkLEDyZC3+8mQt//JkLf/yZC3/8mQt//JkLowAAAAAAAAAAAAAAAAAAAAA9mgvG/NkLfXyZC3/8mQt//JkLf/yZC3/82Qt4fFjKxIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA82ExFfJkLePyZC3/8mQt//JkLf/yZC3/8mQt8/VmKRkAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLXjyZC3/8mQt//JkLf/yZC3/8mQt//JkLb3/bSQHAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLYfyZC3/8mQt//JkLf/yZC3/8mQthwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/YCAI8mQtwfJkLf/yZC3/8mQt//JkLf/yZC3/8mMsdAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP9VKwbyZS3Q8mQt//JkLf/yZC3/8mQt//JkLf/yZC2w/20kBwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLXjyZC3l8mQt5fJkLeXyZC3l8mQteAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP9gIAjyZCyy8mQt//JkLf/yZC3/8mQt//JkLf/zZC3N/2YzBQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADyYi4n8mQt8/JkLf/yZC3/8mQt//JkLf/yZC3/8mUuvvFjKxIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8l4oE/JkLcDyZC3/8mQt//JkLf/yZC3/8mQt//JlLfHxZzAlAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA82UuU/JkLfzyZC3/8mQt//JkLf/yZC3/8mQt//NkLeHyZi88AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADzYy0+8WQt4vJkLf/yZC3/8mQt//JkLf/yZC3/8mQt/PJkLU8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPNlLGjyZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3+8mQunPViMRoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9mgvG/JlLZ3yZC3+8mQt//JkLf/yZC3/8mQt//JkLf/yZC3+8mUtZQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADzZSxo8mQt/PJkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLfjyYy2a8WYuNwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPFmLjfyYy2a8mQt+PJkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLfzyZS1lAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA82UuU/JkLfPyZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLd3yZCyb8mQsY/JjKzvwYi0i8GktEfFjKxLwYi0i8mMrO/JkLGPyZCyb8mQt3vJkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt8vJjLVAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJiLifyZS3Q8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/xZC3O8WcwJQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/ZjMF8WUub/JkLfPyZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/82Qt9fFkLoD/VSsGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPZkLhzzYyyQ82Qt9fJkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLfTzZC2P9WIxGgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8mYzFPFkLG7yZC3L8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZCzJ8WMtbPJeKBMAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9GArGPNlLljzYyyQ82QsuPJkLdnyZC3u8mQt+fJkLfryZC3u8mMs2vNkLLjzZC2P82UuWPRkLBcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP//4Af//wAA//8AAP//AAD/+AAAH/8AAP/wAAAH/wAA/8AAAAP/AAD/gA/wAf8AAP8Af/4A/wAA/gH//4B/AAD8B///4D8AAPgP+B/wHwAA8B/4H/gPAADwP/gf/A8AAOB/+B/+BwAAwP/4H/8DAADA//gf/wMAAMH/+B//gwAAgf/4H/+BAACD//gf/8EAAIP/+B//wQAAA//4H//AAAAH//gf/+AAAAf/+B//4AAAB//4H//gAAAH//gf/+AAAAf/+B//4AAAB//4H//gAAAH//gf/+AAAAf/+B//4AAAA//4H//AAACD//gf/8EAAIP/////wQAAgf////+BAADB/////4MAAMD/+B//AwAAwP/4H/8DAADgf/gf/gcAAPA/+B/8DwAA8B/8P/gPAAD4D///8B8AAPwH///gPwAA/gH//4B/AAD/AH/+AP8AAP+AD/AB/wAA/8AAAAP/AAD/8AAAB/8AAP/4AAAf/wAA//8AAP//AAD//+AH//8AACgAAAAgAAAAQAAAAAEAIAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/1UrBvFlL0fxZC2U8mQtv/JkLdfyZC3z8mQt8/JkLdfyZC2/8WQtlPBiLEb/VSsGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9GArGPFkLJbyZS3x8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLfDxYyyV9GArGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/2AgCPFlLYHyZC308mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3z82Qsf/9tJAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPRgKxjyZC3H8mQt//JkLf/yZC3/8mQt//JkLf/yZC3p82QtpPFjLYPxYy1s8WMtbPFjLYPzZC2k8mQt6fJkLf/yZC3/8mQt//JkLf/yZC3/8mQtxfRgKxgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD0ZCwu8mQt4/JkLf/yZC3/8mQt//JkLf/yZC6t8mMrO/+AAAIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/VVUD8mYvPPJkLa7yZC3/8mQt//JkLf/yZC3/8WQt4vRmLS0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9WYpGfJkLePyZC3/8mQt//JkLf/yZS3V8mItOQAAAAAAAAAAAAAAAAAAAADxYysS9mgvG/ZoLxvxYysSAAAAAAAAAAAAAAAAAAAAAPJjKzvyZC3W8mQt//JkLf/yZC3/8WQt4vRgKxgAAAAAAAAAAAAAAAAAAAAAAAAAAP9gIAjyZC3H8mQt//JkLf/yZC3/8mQtt+5mMw8AAAAAAAAAAAAAAAAAAAAAAAAAAPJlLa/yZC3/8mQt//JlLa8AAAAAAAAAAAAAAAAAAAAAAAAAAOtiJw3yZC2w8mQt//JkLf/yZC3/8mQtxv9tJAcAAAAAAAAAAAAAAAAAAAAA8WQtgvJkLf/yZC3/8mQt//JkLrP/VVUDAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8mUtr/JkLf/yZC3/8mUtrwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP9VVQPyZC218mQt//JkLf/yZC3/8WQugAAAAAAAAAAAAAAAAPVmKRnyZC308mQt//JkLf/yZS3V7VskDgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADyZS2v8mQt//JkLf/yZS2vAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO5mMw/yZC3W8mQt//JkLf/yZC3z9GArGAAAAAAAAAAA8WQul/JkLf/yZC3/8mQt/vFkLjgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJlLa/yZC3/8mQt//JlLa8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJjKzvyZC3/8mQt//JkLf/xYyyVAAAAAP9tJAfyZS3x8mQt//JkLf/yYyysAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8mUtr/JkLf/yZC3/8mUtrwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLbDyZC3/8mQt//JkLfD/VSsG8WMuSPJkLf/yZC3/8mQt//JlLDoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADyZS2v8mQt//JkLf/yZS2vAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8mYvPPJkLf/yZC3/8mQt//BiLEbxZCyW8mQt//JkLf/yZC3n/4AAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJlLa/yZC3/8mQt//JlLa8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/VVUD8mQt6fJkLf/yZC3/8WQtlPJkLcDyZC3/8mQt//JlLqIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8mUtr/JkLf/yZC3/8mUtrwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADzZC2k8mQt//JkLf/yZS6+8mQt2fJkLf/yZC3/8WMtgwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADyZS2v8mQt//JkLf/yZS2vAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLIXyZC3/8mQt//JkLdfyZC3z8mQt//JkLf/zZS5qAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJlLa/yZC3/8mQt//JlLa8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8WMtbPJkLf/yZC3/8mUt8fJkLfPyZC3/8mQt//NkLmkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8mUtr/JkLf/yZC3/8mUtrwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADzZC1r8mQt//JkLf/yZC3z8mQt2/JkLf/yZC3/8WQtggAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADyZS2v8mQt//JkLf/yZS2vAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPFkLITyZC3/8mQt//JkLdjyZC3A8mQt//JkLf/yZS6iAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJlLa/yZC3/8mQt//JlLa8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA82QtpPJkLf/yZC3/8mUuvvFkLpfyZC3/8mQt//JkLef/gAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8mUtr/JkLf/yZC3/8mUtrwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAP+AAALyZC3o8mQt//JkLf/xYyyV8WUtSfJkLf/yZC3/8mQt//JlLDoAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADxYysk8WMvNvFjLzbxYyskAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8mYvPPJkLf/yZC3/8mQt//FlL0f/bSQH8mQt8vJkLf/yZC3/8mUtqgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPFjKxL2aC8b9mgvG/FjKxIAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADyZC6t8mQt//JkLf/yZC3y/20kBwAAAADyZS2Y8mQt//JkLf/yZC3+8WYuNwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8mUtr/JkLf/yZC3/8mUtrwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA8mItOfJkLf7yZC3/8mQt//FkLJYAAAAAAAAAAPViMRrzZC318mQt//JkLf/yZC3T62InDQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADyZS2v8mQt//JkLf/yZS2vAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAO1bJA7yZS3V8mQt//JkLf/yZC309WYpGQAAAAAAAAAAAAAAAPFkLITyZC3/8mQt//JkLf/yZCyy/4AAAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPJlLa/yZC3/8mQt//JlLa8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/VVUD8mQus/JkLf/yZC3/8mQt//FlLYEAAAAAAAAAAAAAAAAAAAAA/2AgCPJkLcfyZC3/8mQt//JkLf/yYy227mYzDwAAAAAAAAAAAAAAAAAAAAAAAAAA9GYtLfRjLkP0Yy5D9GYtLQAAAAAAAAAAAAAAAAAAAAAAAAAA6morDPJkLbDyZC3/8mQt//JkLf/zZC3M/3E5CQAAAAAAAAAAAAAAAAAAAAAAAAAA9WYpGfJkLeTyZC3/8mQt//JkLf/yZC3T8WYuNwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPFkLjjyZS3V8mQt//JkLf/yZC3/8mQt4/RgKxgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9GIrL/JkLeTyZC3/8mQt//JkLf/yZC3+8mQtq/JlLDr/gAACAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/4AAAvJlLDryYyys8mQt/vJkLf/yZC3/8mQt//JkLeP0ZCwuAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA9WYpGfJkLMnyZC3/8mQt//JkLf/yZC3/8mQt//JkLefyZS6i8WQtgvFjLWzxYy1s8WQtgvJkLaPyZC3o8mQt//JkLf/yZC3/8mQt//JkLf/yZC3H9WYpGQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/2AgCPFkLITzZC318mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC308WQtgv9gIAgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPViMRryZS2Y8mQt8vJkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZC3/8mQt//JkLf/yZS3x8WQul/VmKRkAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAD/bSQH8WUtSfFkLJbyZC3B8mQt2PJkLfTyZC308mQt2PJkLcHxZCyW8WMuSP9tJAcAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA//AP//+AAf/+AAD//AGAP/gf+B/wf/4P4Pw/B8H8P4PD/D/Dh/w/4Yf8P+GP/D/xD/w/8A/8P/AP/D/wH/w/+B/8P/gP/D/wD/w/8A/8P/CP///xh///4Yf8P+HD/D/Dwfw/g+D//wfwf/4P+B/4H/wBgD/+AAB//4AB///wD/8oAAAAEAAAACAAAAABACAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPNlLyvyZS2O8mQt0/JkLfPyZC3z8mQt0/JlLY7zZS8rAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAA/1UrBvNlLZPyZC388mQt//JkLePyZC298mQtvfJkLeTyZC3/8mQt/PNkLZL/VSsGAAAAAAAAAAAAAAAA/1UrBvFkLbzyZC3/8mMsw/JjKzv/AAAB5mYzCuZmMwr/AAAB8mYvPPJkLcXyZC3/8WQtu/9mMwUAAAAAAAAAAPNlLZPyZC3/8mMtmv9VVQMAAAAAAAAAAPJkLdjyZC3YAAAAAAAAAAD/gEAE8mQsm/JkLf/zZC6RAAAAAPNjLizyZC388mMsw/9VVQMAAAAAAAAAAAAAAADyZC3Y8mQt2AAAAAAAAAAAAAAAAP+AQATyZC7E8mQt/PNhKyrzYyyQ8mQt//JlLDoAAAAAAAAAAAAAAAAAAAAA8mQt2PJkLdgAAAAAAAAAAAAAAAAAAAAA8mYvPPJkLf/yZS2O8mUt1fFkLeL/AAABAAAAAAAAAAAAAAAAAAAAAPJkLdjyZC3YAAAAAAAAAAAAAAAAAAAAAP8AAAHyZC3k8mQt0/JkLfPxZC27AAAAAAAAAAAAAAAAAAAAAAAAAADyZC3Y8mQt2AAAAAAAAAAAAAAAAAAAAAAAAAAA8mQtvfJlLfHyZC3z82QtugAAAAAAAAAAAAAAAAAAAAAAAAAA8mQt2PJkLdgAAAAAAAAAAAAAAAAAAAAAAAAAAPFkLbzyZC3y8mUt1fFkLeIAAAAAAAAAAAAAAAAAAAAAAAAAAPJkLdjyZC3YAAAAAAAAAAAAAAAAAAAAAP8AAAHyZC3j8mQt0/NjLJDyZC3/8mItOQAAAAAAAAAAAAAAAAAAAADvazEf72sxHwAAAAAAAAAAAAAAAAAAAADyYys78mQt//JlLY7zYy4s8mQt/PJkLcL/VVUDAAAAAAAAAAAAAAAA8mQt2PJkLdgAAAAAAAAAAAAAAAD/VVUD8mMsw/JkLfzzZS8rAAAAAPFjLJXyZC3/8mQtmf9VVQMAAAAAAAAAAPJjLYjyYy2IAAAAAAAAAAD/VVUD8mMtmvJkLf/zZS2TAAAAAAAAAAD/VSsG8mQtvfJkLf/yZC3B8mItOQAAAAAAAAAAAAAAAAAAAADyZSw68mMsw/JkLf/xZC28/1UrBgAAAAAAAAAAAAAAAP9VKwbxYyyV8mQt/fJkLf/xZC3i8WQtvPFkLbzxZC3i8mQt//JkLfzzZS2T/1UrBgAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAPNjLizzYyyQ8mQt1PJkLfTyZC308mQt1PNjLJDzYy4sAAAAAAAAAAAAAAAAAAAAAPgfAADgBwAAx+MAAI5xAACeeQAAPnwAAD58AAA+fAAAPnwAAD58AAA//AAAnnkAAI5xAADH4wAA4AcAAPgfAAA=", 'base64'
  )

function GET() {
  return new server.NextResponse(buffer, {
    headers: {
      'Content-Type': contentType,
      'Cache-Control': "public, max-age=0, must-revalidate",
    },
  })
}

const dynamic = 'force-static'

;// CONCATENATED MODULE: ./node_modules/next/dist/build/webpack/loaders/next-app-loader.js?page=%2Ffavicon.ico%2Froute&name=app%2Ffavicon.ico%2Froute&pagePath=private-next-app-dir%2Ffavicon.ico&appDir=C%3A%5CUsers%5CVadimus%5CDesktop%5Cimobile-back%5Capp&appPaths=%2Ffavicon.ico&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js&basePath=&assetPrefix=&nextConfigOutput=&preferredRegion=&middlewareConfig=e30%3D!

    

    

    

    const options = {"definition":{"kind":"APP_ROUTE","page":"/favicon.ico/route","pathname":"/favicon.ico","filename":"favicon","bundlePath":"app/favicon.ico/route"},"resolvedPagePath":"next-metadata-route-loader?page=%2Ffavicon.ico%2Froute&pageExtensions=tsx&pageExtensions=ts&pageExtensions=jsx&pageExtensions=js!C:\\Users\\Vadimus\\Desktop\\imobile-back\\app\\favicon.ico?__next_metadata__","nextConfigOutput":""}
    const routeModule = new (module_default())({
      ...options,
      userland: favicon_next_metadata_namespaceObject,
    })

    // Pull out the exports that we need to expose from the module. This should
    // be eliminated when we've moved the other routes to the new format. These
    // are used to hook into the route.
    const {
      requestAsyncStorage,
      staticGenerationAsyncStorage,
      serverHooks,
      headerHooks,
      staticGenerationBailout
    } = routeModule

    const originalPathname = "/favicon.ico/route"

    

/***/ })

};
;

// load runtime
var __webpack_require__ = require("../../webpack-runtime.js");
__webpack_require__.C(exports);
var __webpack_exec__ = (moduleId) => (__webpack_require__(__webpack_require__.s = moduleId))
var __webpack_exports__ = __webpack_require__.X(0, [381,981,917,628], () => (__webpack_exec__(84964)));
module.exports = __webpack_exports__;

})();